# Run Tests
name: Run Tests

on:
  # # Run the workflow nightly at 0000 UTC
  # schedule:
  #   - cron: '0 0 * * *'

  # Allow running the workflow manually from the Actions tab
  # All jobs are excluded by default, desired jobs must be selected
  workflow_dispatch:

    inputs:

      project_name:
        description: 'Enter the name of the project to test:'
        type: string
        required: true
        default: ''

      debug_enabled:
        type: boolean
        description: 'Enable tmate debugging (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false


run-name:  ${{ inputs.project_name }}

permissions: {}

jobs:

  tests:

    timeout-minutes: 300

    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: create SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.PY }}
          channels: conda-forge
          auto-activate-base: true
          activate-environment: ""

      - name: check all projects
        if: inputs.project_name == ''
        run: |
          echo "============================================================="
          echo "Check for updates to any configured projects
          echo "============================================================="
          ./benchmark.py -u *.json

      - name: fetch database
        if: inputs.project_name != ''
        run: |
          cd $GITHUB_WORKSPACE/runner

          echo "============================================================="
          echo "Fetch database for ${{ inputs.project_name }}"
          echo "============================================================="
          mkdir data
          cd data
          wget -q openmdao.org/benchmark/test/data/${{ inputs.project_name }}.db
          cd ..

          echo "============================================================="
          echo "Fetch SNOPT source if needed"
          echo "============================================================="
          SNOPT_DIR=`grep snopt ${{ inputs.project_name }}.json | awk -F ' ' '{print $NF}' | tr -d '"'`
          echo "$SNOPT_DIR"
          if [ -n "$SNOPT_DIR" ]; then
            mkdir -p $SNOPT_DIR
            scp -qr ${{ secrets.SNOPT_LOCATION }} $SNOPT_DIR
            ls -l ~
            ls -l $SNOPT_DIR/*
          fi

          echo "============================================================="
          echo "Test ${{ inputs.project_name }}"
          echo "============================================================="
          pip install slack_sdk matplotlib
          ls -l data
          python benchmark.py -u ${{ inputs.project_name }}.json
          ls -l data
          ls -l repos/*

      - name: Setup tmate session
        if: ${{ inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true